compile :
	g++ -std=c++2a -O0 -ggdb *.cpp                                                       \
		-I/usr/include/LIEF-0.11.0-Linux/include -L/usr/lib/LIEF-0.11.0-Linux/lib -lLIEF \
		-I/usr/local/include/Zydis -I/usr/local/include/Zycore -L/usr/local/lib -lZydis  \
		-I..                                                                             \
        -o merge.out
